#!/bin/bash
echo THIS MIGHT TAKE A FEW DECADES
echo zhe ke neng xu yao ji ge shi ji
cd /BJL/C8ins/
sh manpages
sh ianaetc
sh glibc
sh zlib
sh bzip2
sh xz
sh zstd
sh file
sh readline
sh m4
sh bc
sh flex
sh tcl
sh expect
sh dejagnu
sh binutils
